### sign up

POST http://localhost:3000/reports 
content-type: application/json

{
    "make": "toyota",
    "model": "corolla",
    "year": 1980,
    "mileage": 10000,
    "lng": 0,
    "lat": 0,
    "price": 50000
}

### approve an existing report

PATCH http://localhost:3000/reports/5 
content-type: application/json

{
    "approved": true
}

### sign in

POST http://localhost:3000/auth/signin 
content-type: application/json

{
    "email": "test@test111.com",
    "password": "admin123"
}

### sign out

POST http://localhost:3000/auth/signout