### list all
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "test@test.com",
    "password" : "admin123"
}


### Find user
GET http://localhost:3000/auth/1


### Find user by email
GET http://localhost:3000/auth?email=test@test.com


### delete user by id
DELETE http://localhost:3000/auth/1


### update user
PATCH http://localhost:3000/auth/2
content-type: application/json

{
    "email": "test@testmodified.com",
    "password" : "admin123_modified"
}


### update user BAD REQUEST
PATCH http://localhost:3000/auth/1222
content-type: application/json

{
    "email": "test@testmodified.com",
    "password" : "admin123_modified"
}

### Find user  BAD REQUEST
GET http://localhost:3000/auth/1222

### update user  BAD REQUEST
PATCH http://localhost:3000/auth/222
content-type: application/json

{
    "email": "test@testmodified.com",
    "password" : "admin123_modified"
}